const destinations = [
    {
        img: '',
        imgDescription: '',
        title: '',
        subTitle: '',
        content: '',
        url: '',
    },
    {
        img: '',
        imgDescription: '',
        title: '',
        subTitle: '',
        content: '',
        url: '',
    },
    {
        img: '',
        imgDescription: '',
        title: '',
        subTitle: '',
        content: '',
        url: '',
    },
    {
        img: '',
        imgDescription: '',
        title: '',
        subTitle: '',
        content: '',
        url: '',
    },
    {
        img: '',
        imgDescription: '',
        title: '',
        subTitle: '',
        content: '',
        url: '',
    },
    {
        img: '',
        imgDescription: '',
        title: '',
        subTitle: '',
        content: '',
        url: '',
    },
    {
        img: '',
        imgDescription: '',
        title: '',
        subTitle: '',
        content: '',
        url: '',
    },
    {
        img: '',
        imgDescription: '',
        title: '',
        subTitle: '',
        content: '',
        url: '',
    },
];

export default destinations;