const destinations = [
    {
        img: 'images/',
        imgDescription: 'Malaysia Travel',
        title: 'Malaysia',
        subTitle: 'Asia',
        content: '',
        url: '',
    },
    {
        img: 'Thailand Travel',
        imgDescription: 'Thailand Travel',
        title: 'Thailand',
        subTitle: 'Asia',
        content: '',
        url: '',
    },
    {
        img: 'Japan Travel',
        imgDescription: 'Japan Travel',
        title: 'Japan',
        subTitle: 'Asia',
        content: '',
        url: '',
    },
    {
        img: '',
        imgDescription: '',
        title: '',
        subTitle: '',
        content: '',
        url: '',
    },
    {
        img: '',
        imgDescription: '',
        title: '',
        subTitle: '',
        content: '',
        url: '',
    },
    {
        img: '',
        imgDescription: '',
        title: '',
        subTitle: '',
        content: '',
        url: '',
    },
    {
        img: '',
        imgDescription: '',
        title: '',
        subTitle: '',
        content: '',
        url: '',
    },
    {
        img: '',
        imgDescription: '',
        title: '',
        subTitle: '',
        content: '',
        url: '',
    },
];

export default destinations;